### ISSUE TITLE
async in plugin

### ISSUE THREAD

**Issue by manylov** [mullwar/telebot#116]
in main script:
` bot.plug(require("./plugins/auth"));`

in auth.js

```
module.exports = {
  id: "auth",
  defaultConfig: {
  },

  plugin(bot, pluginConfig) {

    bot.mod("message", async data => {
      return data;
    });
  }
};

```
[bot.error] TypeError: Cannot use 'in' operator to search for 'new_chat_members' in undefined
    at TeleBot.message (/home/maxim/projects/bots/testbot/node_modules/telebot/lib/updates.js:51:24)
    at TeleBot.processUpdate (/home/maxim/projects/bots/testbot/node_modules/telebot/lib/telebot.js:62:55)
    at promise.then (/home/maxim/projects/bots/testbot/node_modules/telebot/lib/telebot.js:279:51)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

probably solved - line 51 in node_modules/telebot/lib/updates.js

`            if (!update || !(type in update)) continue;`

**Comment by mehranrasulian** [comment]
Have the same issue with `bot.mod` , had to use a dirty way instead of `bot.mod` just because I need async
