### ISSUE TITLE
Exception on DNS failure

### ISSUE THREAD

**Issue by hostmit** [mullwar/telebot#149]
Hello! If bot is unable to resolve telegram domain, it will get unhanded exception and crash. Should be handled.

**Comment by hostmit** [comment]
[bot.error.webhook] { Error: getaddrinfo ENOTFOUND api.telegram.org api.telegram.org:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api.telegram.org',
  host: 'api.telegram.org',
  port: 443 }
(node:2497) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND api.telegram.org api.telegram.org:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:2497) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2497) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
