### ISSUE TITLE
ERROR - TeleBot: "ReadTimeout occurred, args=(ReadTimeoutError("HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)",),)

### ISSUE THREAD

**Issue by MarsDiplomatToEarth** [mullwar/telebot#181]
2020-07-02 23:18:26,744 (util.py:68 PollingThread) ERROR - TeleBot: "ReadTimeout occurred, args=(ReadTimeoutError("HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)",),)
Traceback (most recent call last):
  File "D:\anaconda\envs\py2\lib\site-packages\telebot\util.py", line 62, in run
    task(*args, **kwargs)
  File "D:\anaconda\envs\py2\lib\site-packages\telebot\__init__.py", line 281, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "D:\anaconda\envs\py2\lib\site-packages\telebot\__init__.py", line 251, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "D:\anaconda\envs\py2\lib\site-packages\telebot\apihelper.py", line 199, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\anaconda\envs\py2\lib\site-packages\telebot\apihelper.py", line 63, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "D:\anaconda\envs\py2\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\anaconda\envs\py2\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "D:\anaconda\envs\py2\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)

**Comment by MarsDiplomatToEarth** [comment]
how can i restart it

**Comment by cikaldev** [comment]
i think your issue is unrelated here, this project is running on NodeJS language,
there was same project name but for Python [https://github.com/KyleJamesWalker/telebot](https://github.com/KyleJamesWalker/telebot)

you may close this issue..
